replicas: 1

extraEnv: []

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate: {}

image:
  repo: recordsansible/ara-api
  tag: latest

service:
  type: ClusterIP

ingress:
  enabled: false
  annotations: {}
  tls: false
  tlsSecret: ara-tls
  hosts:
    - ara.example.com

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  storageClass: ''
