replicas: 1

extraEnv:
  ARA_ALLOWED_HOSTS: "['localhost', '::1', '127.0.0.1', 'ara.example.com']"

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate: {}

image:
  repo: recordsansible/ara-api
  tag: latest

service:
  type: ClusterIP

ingress:
  enabled: false
  annotations: {}
  tls: false
  tlsSecret: ara-tls
  hosts:
    - ara.example.com

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  storageClass: ''

oauth2proxy:
  enabled: false
  config:
    clientID: xxx
    clientSecret: xxx
    cookieSecret: xxx
  extraArgs:
    upstream: http://ara-ara
    provider: keycloak-oidc
    redirect-url: https://ara-web.example.com/oauth2/callback
    oidc-issuer-url: https://<keycloak host>/realms/<your realm>
    # allowed-role: role1
    # allowed-role: role2
    # allowed-group: group1
    # allowed-group: group2
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - ara-web.example.com
    tls:
      - secretName: oauth2-proxy-tls
        hosts:
        - ara-web.example.com
