kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "ara.name" . | quote }}
  labels: {{ include "ara.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.deploymentStrategy.type | quote }}
    {{- if eq .Values.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate: {{ toYaml .Values.deploymentStrategy.rollingUpdate | nindent 6 }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ include "ara.name" . | quote }}
  template:
    metadata:
      labels: {{ include "ara.labels" . | nindent 8 }}
    spec:
      containers:
        - name: ara-api
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          {{- if .Values.extraEnv }}
          env:
            {{ toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8000
            - containerPort: 3000
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /opt/ara
          {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "ara.name" . }}
      {{- else -}}
        - name: data
          emptyDir: {}
      {{- end }}
