kind: Service
apiVersion: v1
metadata:
  name: {{ include "ara.name" . }}
  labels: {{ include "ara.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ara.name" . }}
  ports:
    - name: TCP-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: TCP-3000
      protocol: TCP
      port: 3000
      targetPort: 3000
